[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "jwks-sqlite-server"
version = "0.1.0"
description = "SQLite-backed JWKS demo server for CSCE 3550 Project 2"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
